Rightpoint/Swiftilities

Pod/Classes/Logging/Log.swift
@nbonatsakis removes warnings for the logger
=> added #'s instead of _'s

Pod/Classes/Logging/Log.swift
@nbonatsakis sorry I had branched wrong so the log stuff i did got rolled back, here it is again
=> log fix again

LICENSE
@nbonatsakis updating the license file.
=> updating the license file

.travis.yml, Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Swiftilities.xcscheme, Swiftilities.podspec, deploy.sh
- This is actually CI and Carthage. 
- Definitely want to squash all the commits on this one
=> Carthage Support

Pod/Classes/Views/Textview/TailoredSwiftTextView.swift
- fixes an issue where setting text doesn't trigger notifications to resize
=> Swift 3 - settable .text

Pod/Classes/Deselection/UIViewController+Deselection.swift
For reasoning, see this comment and my followup: https://www.raizlabs.com/dev/2016/05/smarter-animated-row-deselection-ios/#comment-12391
=> Tweak smart deselection

.travis.yml, README.md
adding an only build on push for develop / master to the travis.yml
=> making travis build master / develop

Pod/Classes/Keyboard/Keyboard.swift
=> opened the keyboard class

Pod/Classes/Keyboard/UIView+KeyboardLayoutGuide.swift
added `@nonobjc` to extensions on objc classes where it was missing, addresses #28
=> marked extensions on objc classes as non-objc

Pod/Classes/Logging/Log.swift
=> removed colors, added emoji support

Example/Podfile.lock, Example/Pods/Local Podspecs/Swiftilities.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Swiftilities/Base.lproj/Main.storyboard, Pod/Classes/HairlineView/HairlineView.swift, Swiftilities.podspec
=> added hairline views and example

Example/Podfile.lock, Example/Pods/Local Podspecs/Swiftilities.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/Swiftilities/Info.plist, Pod/Classes/AccessibilityHelpers/AccessibilityHelpers.swift, Swiftilities.podspec
=> added accessibility helpers

Example/Podfile.lock, Example/Pods/Local Podspecs/Swiftilities.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Swiftilities/TintedButtonsViewController.swift, Pod/Classes/ColorHelpers/UIColor+Helpers.swift, Swiftilities.podspec
=> added colorHelpers

Example/Podfile.lock, Example/Pods/Local Podspecs/Swiftilities.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Pod/Classes/StackViewHelpers/UIStackView+Helpers.swift, Swiftilities.podspec
=> added stack helpers

Pod/Classes/Acknowledgements/AcknowledgementViewController.swift
Tweak topAnchor constraint in AcknowledgementViewController, so label doesn't abut navigation bar.
Before:
After:
=> Acknowledgement: Tweak TopAnchor Constraint

Example/Swiftilities.xcodeproj/project.pbxproj, Example/Tests/MathTests.swift, Example/Tests/ValidatorTests.swift, Pod/Classes/FormattedTextField/FormattedTextField.swift, Pod/Classes/Forms/FieldValidator.swift
This has some breaking changes with the validator, but I don't think anyone was using it.
=> Fix validator

.swiftlint.yml, Example/Swiftilities.xcodeproj/project.pbxproj, Example/Swiftilities/App Delegate/AppDelegate.swift, Example/Swiftilities/Views/About View/AboutViewController.swift, Example/Swiftilities/Views/Keyboard Avoidance/KeyboardAvoidanceViewController.swift, Example/Swiftilities/Views/Lifecycle/LogAppearanceBehavior.swift, Example/Swiftilities/Views/Main/MainScreenViewController.swift, Example/Swiftilities/Views/Text Formatting/TextFormattingViewController.swift, Example/Swiftilities/Views/Tinted Buttons/TintedButtonsViewController.swift, Example/Tests/LicenseFormatterTests.swift, Example/Tests/LogTests.swift, Example/Tests/MathTests.swift, Example/Tests/RootViewControllerTests.swift, Pod/Classes/AboutView/FeedbackPresenter.swift, Pod/Classes/DeviceSize/DeviceSize.swift, Pod/Classes/Lifecycle/DefaultBehaviors.swift, Pod/Classes/Logging/Log.swift
=> Add logging handler

Example/Podfile.lock, Example/Pods/Local Podspecs/Swiftilities.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/Swiftilities/Swiftilities.xcconfig, Example/Swiftilities.xcodeproj/project.pbxproj, Example/Swiftilities/SupportingFiles/TestModel.xcdatamodeld/TestModel.xcdatamodel/contents, Example/Tests/CoreDataStackTests.swift, Pod/Classes/CoreDataStack/CoreDataStack.swift, Swiftilities.podspec
- CoreDataStack implementation that simulates NSPersistentContainer with iOS 9 compatability
- Basic unit tests
- Can refine documentation and tests as needed
=> Lightweight Core Data Stack

Pod/Classes/BetterButton/BetterButton.swift
=> Make the StyleAttributes initializer public

Pod/Classes/Lifecycle/Framework/UIViewController+Lifecycle.swift
=> ensure view is loaded before adding a new behavior vc as a child

Swiftilities.podspec
With updated naming for Rightpoint in Podspec
=> Version Bump to 0.21.0

Pod/Classes/Logging/README.md, README.md
Finally did a doc without screenshots! Demonstrate examples of all logging functionality.
=> Add logging documentation
